version: "3.9"

services:
  powerfox2influxdb:
    build: .
    container_name: powerfox2influxdb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - INFLUXDB_HOST=$INFLUXDB_HOST
      - INFLUXDB_PORT=$INFLUXDB_PORT
      - INFLUXDB_USER=$INFLUXDB_USER
      - INFLUXDB_PASS=$INFLUXDB_PASS
      - INFLUXDB_DB_NAME=$INFLUXDB_DB_NAME
      - POWERFOX_REPORT_YEAR=$POWERFOX_REPORT_YEAR
      - POWERFOX_API=$POWERFOX_API
      - POWERFOX_USER=$POWERFOX_USER
      - POWERFOX_PASSWORD=$POWERFOX_PASSWORD
      - POWERFOX_DEVICE_ID=$POWERFOX_DEVICE_ID
      - TZ=$TZ
    command: '/bin/sh -c "while sleep $UPDATE_INTERVAL; do python /app/powerfox2influxdb.py; done"'