version: "3.9"

services:
  powerfox2influxdb:
    build: .
    container_name: powerfox2influxdb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - KEY=$KEY
    command: '/bin/sh -c "while sleep $UPDATE_INTERVAL; do python /app/powerfox2influxdb.py; done"'